In [1]:
import pandas as pd
import numpy as np

In [6]:
dtypes = {'token_address':str, 'from_address':str, 'to_address':str, 'timestamp':str, 'value':np.float64}
AAVE = pd.read_csv('../Data/AAVE_22-07-25.csv', dtype=dtypes)
AAVE = AAVE[AAVE['timestamp'] <= '2022-07-12 23:59:59+00:00']
AAVE.to_csv('../Data/AAVE_22-07-12.csv', index=False)

In [13]:
dtypes = {'token_address':str, 'from_address':str, 'to_address':str, 'timestamp':str, 'value':np.float64}
COMP = pd.read_csv('../Data/COMP_22-07-25.csv', dtype=dtypes)
COMP = COMP[COMP['timestamp'] <= '2022-07-12 23:59:59+00:00']
COMP.to_csv('../Data/COMP_22-07-12.csv', index=False)

In [14]:
dtypes = {'token_address':str, 'from_address':str, 'to_address':str, 'timestamp':str, 'value':np.float64}
Dai20 = pd.read_csv('../Data/Dai_2020-12-31.csv', dtype=dtypes)

In [15]:
Dai20

,token_address,from_address,to_address,block_timestamp,value,timestamp
0,0x6b175474e89094c44da98b954eedeac495271d0f,0xa478c2975ab1ea89e8196811f51a7b7ade33eb11,0x235abfad01eb1bda28ef94087fbaa63e18074926,2020-12-31 23:07:52+00:00,1.611481e+18,2020-12-31
1,0x6b175474e89094c44da98b954eedeac495271d0f,0x564286362092d8e7936f0549571a803b203aaced,0xecd743a85f46e7bd20e207b302a86fb2df8ee45c,2020-12-31 18:17:34+00:00,1.040461e+20,2020-12-31
2,0x6b175474e89094c44da98b954eedeac495271d0f,0x3d687333c7259bb0ca5319462f5c11826987b883,0x2fa96250cf4eafe165ed7cd3f05e32a99e271566,2020-12-31 19:22:45+00:00,1.841313e+22,2020-12-31
3,0x6b175474e89094c44da98b954eedeac495271d0f,0xa863cc2a7a859b2b76128340d07d025a19f0fc9f,0xd4405f0704621dbe9d4dea60e128e0c3b26bddbd,2020-12-31 08:04:00+00:00,3.600000e+21,2020-12-31
4,0x6b175474e89094c44da98b954eedeac495271d0f,0x896dc58182c3b78598c11aa10f940257a1ce32b1,0x5797ed9f762c11300a6fc397414acdd54ac0decb,2020-12-31 08:04:00+00:00,5.843426e+21,2020-12-31
...,...,...,...,...,...,...
6412134,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xa467c1766a2ab1647e3d61e8c593c1d27ac04edb,2019-11-13 22:22:56+00:00,0.000000e+00,2019-11-13
6412135,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0x0c472a1e184056bb5198c2de27dd59c69cd28a22,2019-11-13 22:07:52+00:00,0.000000e+00,2019-11-13
6412136,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0x8d138c01765483cb79d787ce5933f609cbfdabcf,2019-11-13 22:10:04+00:00,0.000000e+00,2019-11-13
6412137,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xb93f14636678d680dcbbed20c77f2b6220b52c39,2019-11-13 21:22:33+00:00,0.000000e+00,2019-11-13
6412138,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xe9c245293dac615c11a5bf26fcec91c3617645e4,2019-11-13 21:45:03+00:00,0.000000e+00,2019-11-13

In [16]:
dtypes = {'token_address':str, 'from_address':str, 'to_address':str, 'timestamp':str, 'value':np.float64}
Dai21 = pd.read_csv('../Data/Dai_2021-12-31.csv', dtype=dtypes)
Dai22 = pd.read_csv('../Data/Dai_2022-12-31.csv', dtype=dtypes)

In [17]:
Dai22 = Dai22[Dai22['timestamp'] <= '2022-07-12 23:59:59+00:00']

In [18]:
Dai22

,token_address,from_address,to_address,block_timestamp,value,timestamp
115537,0x6b175474e89094c44da98b954eedeac495271d0f,0xbeefbabeea323f07c59926295205d3b7a17e8638,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 10:41:28+00:00,6.014800e+21,2022-07-12
115538,0x6b175474e89094c44da98b954eedeac495271d0f,0x0eae044f00b0af300500f090ea00027097d03000,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 23:43:19+00:00,6.148031e+19,2022-07-12
115539,0x6b175474e89094c44da98b954eedeac495271d0f,0x055475920a8c93cffb64d039a8205f7acc7722d3,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 03:23:07+00:00,4.030352e+21,2022-07-12
115540,0x6b175474e89094c44da98b954eedeac495271d0f,0xbeefbabeea323f07c59926295205d3b7a17e8638,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 12:25:03+00:00,7.289700e+21,2022-07-12
115541,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000007f150bd6f54c40a34d7c3d5e9f56,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 00:32:26+00:00,4.754332e+21,2022-07-12
...,...,...,...,...,...,...
1969056,0x6b175474e89094c44da98b954eedeac495271d0f,0x1111111254fb6c44bac0bed2854e76f90643097d,0xb5eb8cb6ced6b6f8e13bcd502fb489db4a726c7b,2022-01-01 10:28:35+00:00,5.606422e+23,2022-01-01
1969057,0x6b175474e89094c44da98b954eedeac495271d0f,0x2a49eae5cca3f050ebec729cf90cc910fadaf7a2,0x1b272cbd2ae16192bcb748797a06b28f8b8539fa,2022-01-01 10:28:35+00:00,1.854708e+19,2022-01-01
1969058,0x6b175474e89094c44da98b954eedeac495271d0f,0xb5eb8cb6ced6b6f8e13bcd502fb489db4a726c7b,0x2a49eae5cca3f050ebec729cf90cc910fadaf7a2,2022-01-01 10:28:35+00:00,5.595209e+23,2022-01-01
1969059,0x6b175474e89094c44da98b954eedeac495271d0f,0x503828976d22510aad0201ac7ec88293211d23da,0xf7e26b6952056f2378b1dd78ae8ca38c89b28aa8,2022-01-01 10:28:35+00:00,4.921417e+18,2022-01-01
1969060,0x6b175474e89094c44da98b954eedeac495271d0f,0x503828976d22510aad0201ac7ec88293211d23da,0xfb78b9a7798aae2dba98271a175c728417206a4e,2022-01-01 18:40:29+00:00,2.927636e+19,2022-01-01

In [24]:
Dai = pd.concat([Dai22, Dai21, Dai20])

In [25]:
Dai

,token_address,from_address,to_address,block_timestamp,value,timestamp
115537,0x6b175474e89094c44da98b954eedeac495271d0f,0xbeefbabeea323f07c59926295205d3b7a17e8638,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 10:41:28+00:00,6.014800e+21,2022-07-12
115538,0x6b175474e89094c44da98b954eedeac495271d0f,0x0eae044f00b0af300500f090ea00027097d03000,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 23:43:19+00:00,6.148031e+19,2022-07-12
115539,0x6b175474e89094c44da98b954eedeac495271d0f,0x055475920a8c93cffb64d039a8205f7acc7722d3,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 03:23:07+00:00,4.030352e+21,2022-07-12
115540,0x6b175474e89094c44da98b954eedeac495271d0f,0xbeefbabeea323f07c59926295205d3b7a17e8638,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 12:25:03+00:00,7.289700e+21,2022-07-12
115541,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000007f150bd6f54c40a34d7c3d5e9f56,0x60594a405d53811d3bc4766596efd80fd545a270,2022-07-12 00:32:26+00:00,4.754332e+21,2022-07-12
...,...,...,...,...,...,...
6412134,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xa467c1766a2ab1647e3d61e8c593c1d27ac04edb,2019-11-13 22:22:56+00:00,0.000000e+00,2019-11-13
6412135,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0x0c472a1e184056bb5198c2de27dd59c69cd28a22,2019-11-13 22:07:52+00:00,0.000000e+00,2019-11-13
6412136,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0x8d138c01765483cb79d787ce5933f609cbfdabcf,2019-11-13 22:10:04+00:00,0.000000e+00,2019-11-13
6412137,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xb93f14636678d680dcbbed20c77f2b6220b52c39,2019-11-13 21:22:33+00:00,0.000000e+00,2019-11-13
6412138,0x6b175474e89094c44da98b954eedeac495271d0f,0x0000000000000000000000000000000000000000,0xe9c245293dac615c11a5bf26fcec91c3617645e4,2019-11-13 21:45:03+00:00,0.000000e+00,2019-11-13

In [26]:
Dai.to_csv('../Data/Dai_22-07-12.csv', index=False)